[package]
name = "rutstedbytes-life"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28.0"
ocl = "0.19.7"
rand = "0.9.1"


[target.'cfg(windows)'.dependencies]
include_dir = "0.7.4"
temp-file = "0.1.9"
